### ISSUE TITLE
Problem with urlparse

### ISSUE THREAD

**Issue by 0uro** [vianney/python-supergenpass#1]
Hello,

I like that soft, but since last system update it doesn't work anymore.
Gives me that message :
Traceback (most recent call last):
  File "/usr/local/bin/supergenpass", line 20, in <module>
    runpy.run_module('supergenpass')
  File "/usr/lib/python2.7/runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/python2.7/dist-packages/supergenpass/**init**.py", line 32, in <module>
    import urllib.parse
ImportError: No module named parse

I have seen that urllib was split into urllib.parse, urllib.request, and urllib.error in Python 3 so I tried forcing python2.7 but I'm getting the same issue.
I modified **init**.py to simply import urllib and parse modules but now I have that :

Traceback (most recent call last):
  File "/usr/local/bin/supergenpass", line 20, in <module>
    runpy.run_module('supergenpass')
  File "/usr/lib/python2.7/runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 114, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/usr/local/lib/python2.7/dist-packages/supergenpass/__main__.py", line 115
    print("Invalid domain name", file=sys.stderr)

I checked for old cache files too (.pyc)
Clearly my skills are not good enough to fix that

**Comment by 0uro** [comment]
Okay, in the end I managed to fix it myself ^^
I can't commit changes with git because I'm facing bugs related to gnutls / curl.

To fix it :
- line 32 in **init**.py, 
  replace : import urllib.parse
  with : import urllib
- line 108 in **main**.py 
  replace : domain = input("Domain name: ")
  with : domain = raw_input("Domain name: ")
- line 115 in **main**.py
  replace : print("Invalid domain name", sys.stderr)
  with : print("Invalid domain name", tmp)
  insert line right after that : sys.stderr.write(tmp)

Kind regards

**Comment by vianney** [comment]
This project requires Python 3.x (see README) and I have no intention to support 2.x. Please feel free to fork if you need Python 2 (not sure  why you would want that though, as most distros include Python 3 by default now).
